# Generated by Django 5.2 on 2025-04-07 18:17

import shortener.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='key',
            field=models.CharField(default=shortener.models.generate_short_key, max_length=6, unique=True),
        ),
    ]
